export const products = [
  {
    id: 1,
    name: "Turmeric Radiance Face Mask",
    brand: "Ayurveda & Co",
    price: 1200,
    image: "/turmeric-face-mask-skincare.jpg",
    category: "Masks",
    rating: 4.8,
    reviews: 124,
    description: "Golden turmeric-infused face mask with gram flour for radiant, glowing skin",
    skinTypes: ["all", "oily", "combination"],
    concerns: ["brightening", "glow", "inflammation"],
    ingredients: ["turmeric", "gram flour", "honey"],
    benefits: ["Anti-inflammatory", "Brightening", "Detoxifying"],
  },
  {
    id: 2,
    name: "Neem & Tea Tree Cleanser",
    brand: "Pure Botanicals",
    price: 650,
    image: "/neem-tea-tree-cleanser.jpg",
    category: "Cleansers",
    rating: 4.6,
    reviews: 89,
    description: "Deep cleansing formula with natural neem and tea tree oil for acne-prone skin",
    skinTypes: ["oily", "combination"],
    concerns: ["acne", "oiliness", "pores"],
    ingredients: ["neem", "tea tree", "tulsi"],
    benefits: ["Acne-fighting", "Deep cleansing", "Antibacterial"],
  },
  {
    id: 3,
    name: "Rose Water Hydrating Serum",
    brand: "Petals & Essence",
    price: 1450,
    image: "/rose-water-serum-hydrating.jpg",
    category: "Serums",
    rating: 4.9,
    reviews: 156,
    description: "Lightweight hydrating serum with rose water and hyaluronic acid",
    skinTypes: ["all", "dry", "sensitive"],
    concerns: ["hydration", "sensitivity", "dryness"],
    ingredients: ["rose water", "hyaluronic acid", "glycerin"],
    benefits: ["Hydrating", "Soothing", "Lightweight"],
  },
  {
    id: 4,
    name: "Sandalwood Silk Moisturizer",
    brand: "Luxury Skin",
    price: 1600,
    image: "/sandalwood-moisturizer-cream.jpg",
    category: "Moisturizers",
    rating: 4.7,
    reviews: 102,
    description: "Luxurious sandalwood-infused moisturizer with silk proteins",
    skinTypes: ["dry", "sensitive", "mature"],
    concerns: ["dryness", "anti-aging", "calm"],
    ingredients: ["sandalwood", "silk protein", "almond oil"],
    benefits: ["Nourishing", "Anti-aging", "Moisturizing"],
  },
  {
    id: 5,
    name: "Hibiscus Anti-Aging Cream",
    brand: "Timeless Beauty",
    price: 1800,
    image: "/hibiscus-anti-aging-cream.jpg",
    category: "Creams",
    rating: 4.8,
    reviews: 98,
    description: "Premium anti-aging cream with hibiscus extract and peptides",
    skinTypes: ["mature", "dry", "combination"],
    concerns: ["wrinkles", "firmness", "anti-aging"],
    ingredients: ["hibiscus", "peptides", "retinol"],
    benefits: ["Anti-aging", "Firming", "Brightening"],
  },
  {
    id: 6,
    name: "Aloe Vera Cooling Gel",
    brand: "Nature's Touch",
    price: 400,
    image: "/aloe-vera-gel-cooling.jpg",
    category: "Gels",
    rating: 4.5,
    reviews: 67,
    description: "Pure aloe vera gel with cooling properties for soothing skin",
    skinTypes: ["all", "sensitive", "oily"],
    concerns: ["sensitivity", "irritation", "cooling"],
    ingredients: ["aloe vera", "cucumber", "mint"],
    benefits: ["Soothing", "Cooling", "Lightweight"],
  },
  {
    id: 7,
    name: "Jasmine Night Oil",
    brand: "Aromatic Wellness",
    price: 950,
    image: "/jasmine-night-oil-skincare.jpg",
    category: "Oils",
    rating: 4.7,
    reviews: 112,
    description: "Nourishing night oil with jasmine and coconut oil",
    skinTypes: ["dry", "mature", "combination"],
    concerns: ["nourishment", "dryness", "anti-aging"],
    ingredients: ["jasmine", "coconut oil", "argan oil"],
    benefits: ["Nourishing", "Anti-aging", "Aromatic"],
  },
  {
    id: 8,
    name: "Brahmi Scalp Treatment",
    brand: "Ayurveda & Co",
    price: 750,
    image: "/brahmi-scalp-treatment-oil.jpg",
    category: "Treatments",
    rating: 4.6,
    reviews: 78,
    description: "Ayurvedic scalp treatment with brahmi and amla for healthy hair",
    skinTypes: ["all"],
    concerns: ["scalp-health", "nourishment"],
    ingredients: ["brahmi", "amla", "sesame oil"],
    benefits: ["Nourishing", "Strengthening", "Cooling"],
  },
  {
    id: 9,
    name: "Vitamin C Brightening Serum",
    brand: "Radiance Labs",
    price: 1350,
    image: "/vitamin-c-serum-brightening.jpg",
    category: "Serums",
    rating: 4.9,
    reviews: 203,
    description: "Advanced vitamin C serum with 20% pure ascorbic acid for intense brightening and radiance",
    skinTypes: ["all", "oily", "combination", "sensitive"],
    concerns: ["brightening", "anti-aging", "dark-spots", "glow"],
    ingredients: ["vitamin c", "hyaluronic acid", "ferulic acid", "vitamin e", "green tea extract", "aloe vera"],
    benefits: ["Brightening", "Anti-aging", "Antioxidant", "Glow-enhancing", "Dark spot reduction"],
  },
]
